### ISSUE TITLE
Symfony 3.0 with FOSRestBundle doesn`t assign value to enum field 

### ISSUE THREAD

**Issue by krombox** [fre5h/DoctrineEnumBundle#46] opened 2016-01-29 12:42 UTC
I have started develop simple API with Symfony 3.0.

I have into trouble with FOSRestBundle form post action. I send json body via POST method.

``` PHP
/**     
     * @Rest\View(
     *  templateVar = "form",
     *  template = "KromboxMainBundle:Api/CriteriaUserAnswer:new.html.twig"
     * )
     * @Rest\RequestParam(
     *   name="answer",
     * )     
     * @FW\Security("has_role('ROLE_USER')")
     */
    public function postCriteriaUserAnswerAction(Criteria $criteria, Request $request)
    {        
        $criteriaUserAnswer = new CriteriaUserAnswer();
        $criteriaUserAnswer
                ->setCriteria($criteria)
                ->setUser($this->getUser())
        ;                                              
        $form = $this->get('form.factory')->createNamed(null, CriteriaUserAnswerType::class, $criteriaUserAnswer);        
        $form->submit($request);

        if ($form->isValid()) {
            echo 'valid';die();
        } 

        return $form;                        
    }
```

CriteriaUserAnswer Entity has an enum type field answer.  Request->request->get('answer') contains right value(string 'no');. But after $form->handleRequest() answer is still empty. 

I solved this problem by downgrading to Symfony 2.8 in case of this is not strict for me at this moment. But if i should to develop on 3.0 version i`ll have a problem. 

Does someone have this issue?

**Comment by fre5h** [comment] 2016-02-19 15:02
Please check the version v4.2, it should be fixed there.

**Comment by fre5h** [comment] 2016-02-19 15:08
@krombox Please give feedback if your issue was fixed

**Comment by krombox** [comment] 2016-06-13 19:34
Hello. Sorry for delay. Since some time i am back to use Symfony 3.x (3.1.1-DEV) in conjunction with your awesome bundle(v4.6.2). Issue was fixed. Thank you very much.
But i found that issue reproduced when i trying to use ``PUT`` instead of ``POST`` method

**Comment by fre5h** [comment] 2016-06-13 20:19
I guess you use PUT for updates. So maybe the cause is wrong logic for updates. Please give some examples of your code to investigate this issue

**Comment by krombox** [comment] 2016-06-13 20:24
Yes, i am using PUT for updates, but what is the difference? Code is the same as in my first post
just replace ``postCriteriaUserAnswerAction`` with ``putCriteriaUserAnswerAction``

**Comment by fre5h** [comment] 2016-06-13 20:32
Maybe difference is in the way of handling response, I am not sure. Need to investigate this case.

**Comment by fre5h** [comment] 2016-10-08 14:06
@krombox Is it still actual?

**Closed** 2016-12-28 07:09 UTC
Labels: bug
