### ISSUE TITLE
instanceof vs get_parent_class

### ISSUE THREAD

**Issue by gplanchat** [fre5h/DoctrineEnumBundle#60] opened 2016-08-11 09:33 UTC
I seen the use of `get_parent_class` in https://github.com/fre5h/DoctrineEnumBundle/blob/master/Form/EnumTypeGuesser.php#L89

Why the choice of using this function instead of the `instanceof` operator ? Is it to prevent from types inheritance ?

**Comment by fre5h** [comment] 2016-08-12 07:37
Good question. I found the commit which added this https://github.com/fre5h/DoctrineEnumBundle/commit/4f0b7b6b15865fbc1cef8c2144b1dffcc6a21aeb

It was 2,5 years ago, unfortunately I don't remember the cause for this update. But the commit message says `Force EnumTypeGuesser to process only AbstractEnumType and skip other registered DBAL types`. Looks that I had some problems with it.

But your notice makes a sense. Can you describe your case. Maybe it is really has a sense to change it to `instanceof`.

**Comment by gplanchat** [comment] 2016-08-12 09:04
I have no actual use case, I was just wondering why. Eg: if it was a deliberate decision for code consistency or a convention or linked to Doctrine limitations.

**Comment by fre5h** [comment] 2016-08-12 09:11
I don't remember :( so can be debated :)

**Comment by gplanchat** [comment] 2016-08-12 14:27
It could be a long debate : reflection (`get_parent_class`) vs operator (`instanceof`).

As long as it does not add functional restrictions (if Doctrine supports it), I would prefer the latter :) It is my personal choice. The potential speed gains with `instanceof` may probably not be measurable in a classic production environment.

Anyway, the bundle works without change :)

**Comment by fre5h** [comment] 2016-08-15 19:34
Found the reason

```php
$abstractEnumTypeFullClassName = 'Fresh\DoctrineEnumBundle\DBAL\Types\AbstractEnumType';
if (get_parent_class($enumTypeFullClassName) !== $abstractEnumTypeFullClassName) {
    return null;
}
```

In this case $enumTypeFullClassName is a string that's why `instanceof` cannot be used here.

**Comment by gplanchat** [comment] 2016-08-16 10:44
Indeed, it makes sense :)

**Comment by artursvonda** [comment] 2017-09-05 12:57
Can we re-open this? My use-case is that I have my own abstract enum parent class that adds few convenience methods. But now suddenly my form fields aren't guessed correct. Also, `instanceof` supports strings according to http://php.net/manual/en/language.operators.type.php. I'm open to creating a PR for this.

**Comment by fre5h** [comment] 2017-09-06 08:56
@artursvonda I think yes, you can submit your PR. But please follow the code style and tests. As I understood you propose something like this

```php
if (!$enumTypeFullClassName instanceof AbstractEnumType::class) {
    return null;
}
```

**Comment by artursvonda** [comment] 2017-09-06 08:59
Not sure this syntax will work. We can do
```
if (!$enumTypeFullClassName instanceof $abstractEnumTypeFullClassName) {
    return null;
}
```
Also, I'd like to push this change to both 4.x and 5.x version as we're still stuck with 4.x (can't upgrade to Symfony 3 because of Sonata Admin Bundle). How should I approach this? Should I just copy the path to both trees and create separate PRs? Or you'll handle backporting yourself?

**Comment by fre5h** [comment] 2017-09-06 09:04
For version 4.x submit your PR to https://github.com/fre5h/DoctrineEnumBundle/tree/4.x I will create a new patch version for it.
And for version 5.x I will perform fix by myself.

**Comment by fre5h** [comment] 2017-09-06 09:20
@artursvonda  `$enumTypeFullClassName` is not an instantiated object of class AbstractEnumType, it is a string. But `instanceof` expects an object parameter for the left side.

**Comment by artursvonda** [comment] 2017-09-06 09:21
Yes, just realised that while writing the test. So will use `is_subclass_of` which supports string class names.

**Comment by fre5h** [comment] 2017-09-06 09:46
@artursvonda Check the new patch version v4.8.2. If you find some issues with this patch, then new patch is welcome :)
I will add same fix to 5.x bit later

**Comment by artursvonda** [comment] 2017-09-06 09:47
Thank you! Very appreciate your quick response.

**Comment by artursvonda** [comment] 2017-09-06 12:39
Looks like there are issues with 4.8.2. Looks like it requires Symfony 3+.

**Comment by fre5h** [comment] 2017-09-06 13:09
Yes. Sorry. I made a mistake. Created a new version from master. Wait few minutes I will fix it

**Comment by fre5h** [comment] 2017-09-06 13:16
@artursvonda Check again. Should be fixed

**Comment by artursvonda** [comment] 2017-09-06 13:50
Yes, seems to be working fine now. Thanks! :)

**Closed** 2017-11-12 07:18 UTC
Labels: question
